version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  api:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - ./packages/api:/app/packages/api
    depends_on:
      - db
      - redis
